services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: meuapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d # scripts executados na criação

volumes:
  pgdata:
